# Content managed by Project Forge, see [projectforge.md] for details.
# http://goreleaser.com
project_name: loadtoad

archives:
  - format: zip
    wrap_in_directory: "false"
    files:
      - none*

brews:
  -
    repository:
      owner: "kyleu"
      name: "homebrew-kyleu"
    commit_author:
      name: "Kyle U"
      email: "loadtoad@kyleu.com"
    folder: Formula
    homepage: "https://loadtoad.kyleu.dev"
    description: "Load Toad helps you test your web application using HTTP Archive (.har) files"
    license: "CC0"
    skip_upload: "false"
    install: "bin.install \"loadtoad\""

changelog:
  use: "github"

checksum:
  name_template: "checksums.txt"
  extra_files:
    - glob: "./build/dist/*_desktop.dmg"
    - glob: "./build/dist/*_desktop.zip"
    - glob: "./build/dist/*_aar.zip"
    - glob: "./build/dist/*_apk.zip"
    - glob: "./build/dist/*_framework.zip"
    - glob: "./build/dist/*_app.zip"
    # $PF_SECTION_START(checksums)$
    # $PF_SECTION_END(checksums)$

dockers:
  -
    image_templates:
      - "ghcr.io/kyleu/loadtoad:{{ trimprefix .Tag \"v\" }}"
      - "ghcr.io/kyleu/loadtoad:latest"
    dockerfile: ./tools/release/Dockerfile.release
  -
    image_templates:
      - "ghcr.io/kyleu/loadtoad:{{ trimprefix .Tag \"v\" }}-debug"
      - "ghcr.io/kyleu/loadtoad:latest-debug"
    dockerfile: ./tools/release/Dockerfile.debug

dist: "build/dist"

release:
  draft: false
  header: |
    ## {{ .Version }} ({{ .Date }})
    See https://loadtoad.kyleu.dev for download links and documentation
    ## Main downloads
    - [Linux Intel 64 bit](https://github.com/kyleu/loadtoad/releases/download/{{ .Tag }}/loadtoad_{{ .Version }}_linux_amd64.zip)
    - [MacOS Universal](https://github.com/kyleu/loadtoad/releases/download/{{ .Tag }}/loadtoad_{{ .Version }}_darwin_all.zip)
    - [Windows Intel 64 bit](https://github.com/kyleu/loadtoad/releases/download/{{ .Tag }}/loadtoad_{{ .Version }}_windows_amd64.zip)

  extra_files:
    - glob: "./build/dist/*.dmg"
    - glob: "./build/dist/*_desktop.zip"
    - glob: "./build/dist/*_aar.zip"
    - glob: "./build/dist/*_apk.zip"
    - glob: "./build/dist/*_framework.zip"
    - glob: "./build/dist/*_app.zip"
    # $PF_SECTION_START(releasefiles)$
    # $PF_SECTION_END(releasefiles)$

signs:
  - artifacts: checksum

snapshot:
  name_template: "{{ .Tag }}"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: "zip"

universal_binaries:
- id: "darwin"
  replace: false
  name_template: '{{ .ProjectName }}'
  hooks:
    # This is a good place to put one-time use scripts
    post:
      - "./bin/build/android.sh {{ .Version }}"
      - "./bin/build/ios.sh {{ .Version }}"
      - "./bin/build/desktop.release.sh {{ .Version }}"
      - "./tools/notarize/notarize.sh"
      # $PF_SECTION_START(extrascripts)$
      # $PF_SECTION_END(extrascripts)$

builds:
  - id: "darwin"
    goos:
      - darwin
    goarch:
      - "amd64"
      - "arm64"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "linux"
    goos:
      - "linux"
    goarch:
      - "386"
      - "amd64"
      - "arm64"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "linux-arm"
    goos:
      - "linux"
    goarch:
      - "arm"
    goarm:
      - "5"
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "linux-mips"
    goos:
      - "linux"
    goarch:
      - "mips"
      - "mipsle"
      - "mips64"
      - "mips64le"
    gomips:
      - "hardfloat"
      - "softfloat"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "windows"
    goos:
      - "windows"
    goarch:
      - "amd64"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "windows_386"
    goos:
      - "windows"
    goarch:
      - "386"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "windows-arm"
    goos:
      - "windows"
    goarch:
      - "arm"
      - "arm64"
    goarm:
      - "5"
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "freebsd"
    goos:
      - "freebsd"
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "5"
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "netbsd"
    goos:
      - "netbsd"
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "openbsd"
    goos:
      - "openbsd"
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "5"
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
