# Content managed by Project Forge, see [projectforge.md] for details.
# http://goreleaser.com
project_name: loadtoad

archives:
  - format: zip
    wrap_in_directory: "false"
    files:
      - none*

changelog:
  skip: true

checksum:
  name_template: "checksums.txt"
  extra_files:
    - glob: "./build/dist/*_notarized.zip"
    # $PF_SECTION_START(checksums)$
    # $PF_SECTION_END(checksums)$

dockers:
  -
    image_templates:
      - "ghcr.io/kyleu/loadtoad:{{ trimprefix .Tag \"v\" }}"
      - "ghcr.io/kyleu/loadtoad:latest"
    dockerfile: ./tools/release/Dockerfile.release
  -
    image_templates:
      - "ghcr.io/kyleu/loadtoad:{{ trimprefix .Tag \"v\" }}-debug"
      - "ghcr.io/kyleu/loadtoad:latest-debug"
    dockerfile: ./tools/release/Dockerfile.debug

dist: "build/dist"

release:
  draft: false
  header: |
    ## {{ .Version }} ({{ .Date }})
    See https://github.com/kyleu/loadtoad for download links and documentation
    ## Main downloads
    - [Linux Intel 64 bit](https://github.com/kyleu/loadtoad/releases/download/{{ .Tag }}/loadtoad_{{ .Version }}_linux_amd64.zip)
    - [MacOS Universal](https://github.com/kyleu/loadtoad/releases/download/{{ .Tag }}/loadtoad_{{ .Version }}_darwin_all.zip)
    - [Windows Intel 64 bit](https://github.com/kyleu/loadtoad/releases/download/{{ .Tag }}/loadtoad_{{ .Version }}_windows_amd64.zip)

  extra_files:
    - glob: "./build/dist/*_notarized.zip"
    # $PF_SECTION_START(releasefiles)$
    # $PF_SECTION_END(releasefiles)$

signs:
  - artifacts: checksum

snapshot:
  name_template: "{{ .Tag }}"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"
  format: "zip"

universal_binaries:
- id: "darwin"
  replace: false
  name_template: '{{ .ProjectName }}'
  hooks:
    # This is a good place to put one-time use scripts
    post:
      - "./tools/notarize/notarize.sh"
      # $PF_SECTION_START(extrascripts)$
      # $PF_SECTION_END(extrascripts)$

builds:
  - id: "darwin"
    goos:
      - darwin
    goarch:
      - "amd64"
      - "arm64"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "linux"
    goos:
      - "linux"
    goarch:
      - "amd64"
      - "arm64"
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: "windows"
    goos:
      - "windows"
    goarch:
      - "amd64"
    mod_timestamp: "{{ .CommitTimestamp }}"
