// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vscripting/Detail.html:2
package vscripting

//line views/vscripting/Detail.html:2
import (
	"github.com/kyleu/loadtoad/app"
	"github.com/kyleu/loadtoad/app/controller/cutil"
	"github.com/kyleu/loadtoad/views/components"
	"github.com/kyleu/loadtoad/views/layout"
)

//line views/vscripting/Detail.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vscripting/Detail.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vscripting/Detail.html:9
type Detail struct {
	layout.Basic
	Path    string
	Script  string
	Results map[string]string
}

//line views/vscripting/Detail.html:16
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vscripting/Detail.html:16
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="/scripting/`)
//line views/vscripting/Detail.html:18
	qw422016.N().U(p.Path)
//line views/vscripting/Detail.html:18
	qw422016.N().S(`/edit"><button type="button">Edit</button></a></div>
    <h3>`)
//line views/vscripting/Detail.html:19
	components.StreamSVGRefIcon(qw422016, `file-code`, ps)
//line views/vscripting/Detail.html:19
	qw422016.N().S(` `)
//line views/vscripting/Detail.html:19
	qw422016.E().S(p.Path)
//line views/vscripting/Detail.html:19
	qw422016.N().S(`</h3>
    <div class="mt">
`)
//line views/vscripting/Detail.html:21
	out, err := cutil.FormatLang(p.Script, "js")

//line views/vscripting/Detail.html:22
	if err == nil {
//line views/vscripting/Detail.html:22
		qw422016.N().S(`      `)
//line views/vscripting/Detail.html:23
		qw422016.N().S(out)
//line views/vscripting/Detail.html:23
		qw422016.N().S(`
`)
//line views/vscripting/Detail.html:24
	} else {
//line views/vscripting/Detail.html:24
		qw422016.N().S(`      `)
//line views/vscripting/Detail.html:25
		qw422016.E().S(err.Error())
//line views/vscripting/Detail.html:25
		qw422016.N().S(`
`)
//line views/vscripting/Detail.html:26
	}
//line views/vscripting/Detail.html:26
	qw422016.N().S(`    </div>
  </div>
  `)
//line views/vscripting/Detail.html:29
	if len(p.Results) > 0 {
//line views/vscripting/Detail.html:29
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vscripting/Detail.html:31
		components.StreamSVGRefIcon(qw422016, `play`, ps)
//line views/vscripting/Detail.html:31
		qw422016.N().S(` Results</h3>
    <div class="mt">
      <table>
        <thead>
          <tr>
            <th>Example</th>
            <th>Result</th>
          </tr>
        </thead>
        <tbody>
`)
//line views/vscripting/Detail.html:41
		for k, v := range p.Results {
//line views/vscripting/Detail.html:41
			qw422016.N().S(`          <tr>
            <td>`)
//line views/vscripting/Detail.html:43
			qw422016.E().S(k)
//line views/vscripting/Detail.html:43
			qw422016.N().S(`</td>
            <td>`)
//line views/vscripting/Detail.html:44
			qw422016.E().S(v)
//line views/vscripting/Detail.html:44
			qw422016.N().S(`</td>
          </tr>
`)
//line views/vscripting/Detail.html:46
		}
//line views/vscripting/Detail.html:46
		qw422016.N().S(`        </tbody>
      </table>
    </div>
  </div>
`)
//line views/vscripting/Detail.html:51
	}
//line views/vscripting/Detail.html:52
}

//line views/vscripting/Detail.html:52
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vscripting/Detail.html:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vscripting/Detail.html:52
	p.StreamBody(qw422016, as, ps)
//line views/vscripting/Detail.html:52
	qt422016.ReleaseWriter(qw422016)
//line views/vscripting/Detail.html:52
}

//line views/vscripting/Detail.html:52
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vscripting/Detail.html:52
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vscripting/Detail.html:52
	p.WriteBody(qb422016, as, ps)
//line views/vscripting/Detail.html:52
	qs422016 := string(qb422016.B)
//line views/vscripting/Detail.html:52
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vscripting/Detail.html:52
	return qs422016
//line views/vscripting/Detail.html:52
}
