// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vworkflow/Detail.html:1
package vworkflow

//line views/vworkflow/Detail.html:1
import (
	"github.com/kyleu/loadtoad/app"
	"github.com/kyleu/loadtoad/app/controller/cutil"
	"github.com/kyleu/loadtoad/app/loadtoad"
	"github.com/kyleu/loadtoad/views/components"
	"github.com/kyleu/loadtoad/views/layout"
)

//line views/vworkflow/Detail.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vworkflow/Detail.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vworkflow/Detail.html:9
type Detail struct {
	layout.Basic
	Workflow *loadtoad.Workflow
}

//line views/vworkflow/Detail.html:14
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkflow/Detail.html:14
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="#modal-workflow"><button type="button">JSON</button></a></div>
    `)
//line views/vworkflow/Detail.html:17
	components.StreamJSONModal(qw422016, "workflow", "Workflow", p.Workflow, 3)
//line views/vworkflow/Detail.html:17
	qw422016.N().S(`
    <h3>`)
//line views/vworkflow/Detail.html:18
	components.StreamSVGRefIcon(qw422016, `sitemap`, ps)
//line views/vworkflow/Detail.html:18
	qw422016.N().S(` `)
//line views/vworkflow/Detail.html:18
	qw422016.E().S(p.Workflow.Title())
//line views/vworkflow/Detail.html:18
	qw422016.N().S(`</h3>
    <div class="mt">
      <a href="`)
//line views/vworkflow/Detail.html:20
	qw422016.E().S(p.Workflow.WebPath())
//line views/vworkflow/Detail.html:20
	qw422016.N().S(`/run"><button>Run</button></a>
    </div>
  </div>
`)
//line views/vworkflow/Detail.html:23
}

//line views/vworkflow/Detail.html:23
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkflow/Detail.html:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkflow/Detail.html:23
	p.StreamBody(qw422016, as, ps)
//line views/vworkflow/Detail.html:23
	qt422016.ReleaseWriter(qw422016)
//line views/vworkflow/Detail.html:23
}

//line views/vworkflow/Detail.html:23
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vworkflow/Detail.html:23
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkflow/Detail.html:23
	p.WriteBody(qb422016, as, ps)
//line views/vworkflow/Detail.html:23
	qs422016 := string(qb422016.B)
//line views/vworkflow/Detail.html:23
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkflow/Detail.html:23
	return qs422016
//line views/vworkflow/Detail.html:23
}
