// Code generated by qtc from "List.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vworkflow/List.html:1
package vworkflow

//line views/vworkflow/List.html:1
import (
	"github.com/kyleu/loadtoad/app"
	"github.com/kyleu/loadtoad/app/controller/cutil"
	"github.com/kyleu/loadtoad/app/loadtoad"
	"github.com/kyleu/loadtoad/views/components"
	"github.com/kyleu/loadtoad/views/layout"
)

//line views/vworkflow/List.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vworkflow/List.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vworkflow/List.html:9
type List struct {
	layout.Basic
	Workflows loadtoad.Workflows
}

//line views/vworkflow/List.html:14
func (p *List) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkflow/List.html:14
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/vworkflow/List.html:16
	components.StreamSVGRefIcon(qw422016, `sitemap`, ps)
//line views/vworkflow/List.html:16
	qw422016.N().S(` Workflows</h3>
    <div class="mt">`)
//line views/vworkflow/List.html:17
	StreamTable(qw422016, p.Workflows, ps)
//line views/vworkflow/List.html:17
	qw422016.N().S(`</div>
  </div>
`)
//line views/vworkflow/List.html:19
}

//line views/vworkflow/List.html:19
func (p *List) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkflow/List.html:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkflow/List.html:19
	p.StreamBody(qw422016, as, ps)
//line views/vworkflow/List.html:19
	qt422016.ReleaseWriter(qw422016)
//line views/vworkflow/List.html:19
}

//line views/vworkflow/List.html:19
func (p *List) Body(as *app.State, ps *cutil.PageState) string {
//line views/vworkflow/List.html:19
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkflow/List.html:19
	p.WriteBody(qb422016, as, ps)
//line views/vworkflow/List.html:19
	qs422016 := string(qb422016.B)
//line views/vworkflow/List.html:19
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkflow/List.html:19
	return qs422016
//line views/vworkflow/List.html:19
}

//line views/vworkflow/List.html:21
func StreamTable(qw422016 *qt422016.Writer, workflows loadtoad.Workflows, ps *cutil.PageState) {
//line views/vworkflow/List.html:21
	qw422016.N().S(`
  <table class="min-200">
    <thead>
      <tr>
        <th class="shrink">Name</th>
        <th>Requests</th>
      </tr>
    </thead>
    <tbody>
`)
//line views/vworkflow/List.html:30
	for _, w := range workflows {
//line views/vworkflow/List.html:30
		qw422016.N().S(`      <tr>
        <td><a href="`)
//line views/vworkflow/List.html:32
		qw422016.E().S(w.WebPath())
//line views/vworkflow/List.html:32
		qw422016.N().S(`">`)
//line views/vworkflow/List.html:32
		qw422016.E().S(w.Title())
//line views/vworkflow/List.html:32
		qw422016.N().S(`</a></td>
        <td>`)
//line views/vworkflow/List.html:33
		qw422016.N().D(len(w.RequestKeys))
//line views/vworkflow/List.html:33
		qw422016.N().S(`</td>
      </tr>
`)
//line views/vworkflow/List.html:35
	}
//line views/vworkflow/List.html:35
	qw422016.N().S(`    </tbody>
  </table>
`)
//line views/vworkflow/List.html:38
}

//line views/vworkflow/List.html:38
func WriteTable(qq422016 qtio422016.Writer, workflows loadtoad.Workflows, ps *cutil.PageState) {
//line views/vworkflow/List.html:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkflow/List.html:38
	StreamTable(qw422016, workflows, ps)
//line views/vworkflow/List.html:38
	qt422016.ReleaseWriter(qw422016)
//line views/vworkflow/List.html:38
}

//line views/vworkflow/List.html:38
func Table(workflows loadtoad.Workflows, ps *cutil.PageState) string {
//line views/vworkflow/List.html:38
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkflow/List.html:38
	WriteTable(qb422016, workflows, ps)
//line views/vworkflow/List.html:38
	qs422016 := string(qb422016.B)
//line views/vworkflow/List.html:38
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkflow/List.html:38
	return qs422016
//line views/vworkflow/List.html:38
}
