// Code generated by qtc from "List.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vworkflow/List.html:1
package vworkflow

//line views/vworkflow/List.html:1
import (
	"github.com/kyleu/loadtoad/app"
	"github.com/kyleu/loadtoad/app/controller/cutil"
	"github.com/kyleu/loadtoad/app/loadtoad"
	"github.com/kyleu/loadtoad/views/components"
	"github.com/kyleu/loadtoad/views/layout"
)

//line views/vworkflow/List.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vworkflow/List.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vworkflow/List.html:9
type List struct {
	layout.Basic
	Workflows loadtoad.Workflows
}

//line views/vworkflow/List.html:14
func (p *List) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkflow/List.html:14
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="/workflow/new"><button>New</button></a></div>
    <h3>`)
//line views/vworkflow/List.html:17
	components.StreamSVGRefIcon(qw422016, `sitemap`, ps)
//line views/vworkflow/List.html:17
	qw422016.N().S(` Workflows</h3>
    <div class="mt">`)
//line views/vworkflow/List.html:18
	StreamTable(qw422016, p.Workflows, ps)
//line views/vworkflow/List.html:18
	qw422016.N().S(`</div>
  </div>
`)
//line views/vworkflow/List.html:20
}

//line views/vworkflow/List.html:20
func (p *List) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkflow/List.html:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkflow/List.html:20
	p.StreamBody(qw422016, as, ps)
//line views/vworkflow/List.html:20
	qt422016.ReleaseWriter(qw422016)
//line views/vworkflow/List.html:20
}

//line views/vworkflow/List.html:20
func (p *List) Body(as *app.State, ps *cutil.PageState) string {
//line views/vworkflow/List.html:20
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkflow/List.html:20
	p.WriteBody(qb422016, as, ps)
//line views/vworkflow/List.html:20
	qs422016 := string(qb422016.B)
//line views/vworkflow/List.html:20
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkflow/List.html:20
	return qs422016
//line views/vworkflow/List.html:20
}

//line views/vworkflow/List.html:22
func StreamTable(qw422016 *qt422016.Writer, workflows loadtoad.Workflows, ps *cutil.PageState) {
//line views/vworkflow/List.html:22
	qw422016.N().S(`
  <table class="min-200">
    <thead>
      <tr>
        <th class="shrink">Name</th>
        <th>Tests</th>
        <th>Replacements</th>
        <th>Scripts</th>
      </tr>
    </thead>
    <tbody>
`)
//line views/vworkflow/List.html:33
	for _, w := range workflows {
//line views/vworkflow/List.html:33
		qw422016.N().S(`      <tr>
        <td><a href="`)
//line views/vworkflow/List.html:35
		qw422016.E().S(w.WebPath())
//line views/vworkflow/List.html:35
		qw422016.N().S(`">`)
//line views/vworkflow/List.html:35
		qw422016.E().S(w.Title())
//line views/vworkflow/List.html:35
		qw422016.N().S(`</a></td>
        <td>`)
//line views/vworkflow/List.html:36
		qw422016.N().D(len(w.Tests))
//line views/vworkflow/List.html:36
		qw422016.N().S(`</td>
        <td>`)
//line views/vworkflow/List.html:37
		qw422016.N().D(len(w.Replacements))
//line views/vworkflow/List.html:37
		qw422016.N().S(`</td>
        <td>`)
//line views/vworkflow/List.html:38
		qw422016.N().D(len(w.Scripts))
//line views/vworkflow/List.html:38
		qw422016.N().S(`</td>
      </tr>
`)
//line views/vworkflow/List.html:40
	}
//line views/vworkflow/List.html:40
	qw422016.N().S(`    </tbody>
  </table>
`)
//line views/vworkflow/List.html:43
}

//line views/vworkflow/List.html:43
func WriteTable(qq422016 qtio422016.Writer, workflows loadtoad.Workflows, ps *cutil.PageState) {
//line views/vworkflow/List.html:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkflow/List.html:43
	StreamTable(qw422016, workflows, ps)
//line views/vworkflow/List.html:43
	qt422016.ReleaseWriter(qw422016)
//line views/vworkflow/List.html:43
}

//line views/vworkflow/List.html:43
func Table(workflows loadtoad.Workflows, ps *cutil.PageState) string {
//line views/vworkflow/List.html:43
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkflow/List.html:43
	WriteTable(qb422016, workflows, ps)
//line views/vworkflow/List.html:43
	qs422016 := string(qb422016.B)
//line views/vworkflow/List.html:43
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkflow/List.html:43
	return qs422016
//line views/vworkflow/List.html:43
}
