// Code generated by qtc from "Script.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vworkflow/Script.html:1
package vworkflow

//line views/vworkflow/Script.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vworkflow/Script.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vworkflow/Script.html:1
func streamstartScript(qw422016 *qt422016.Writer, ch string, pth string) {
//line views/vworkflow/Script.html:1
	qw422016.N().S(`
  <script>
    let sock;
    function open() {
      console.log("[Open]");
    }
    function recv(m) {
      let el = document.querySelector("#entry-placeholder-" + m.param.idx);
      if (!el) {
        if (m.param.idx === -1) {
          el = document.querySelector("#results");
        } else {
          throw "invalid index [" + m.param.idx + "]";
        }
      }
      const logs = el.querySelector(".logs");
      if (!logs) {
        throw "invalid logs for index [" + m.param.idx + "]";
      }
      switch (m.cmd) {
        case "log":
          const logEl = document.createElement("div");
          logEl.innerText = " - " + m.param.ctx;
          logs.appendChild(logEl);
          break;
        case "error":
          const failures = document.querySelector("#results .failures");
          let fc = parseInt(failures.innerText, 10);
          failures.innerText = (fc + 1).toString(10);
          const errEl = document.createElement("div");
          errEl.innerText = " - ERROR: " + m.param.ctx;
          errEl.classList.add("error");
          logs.appendChild(errEl);
          break;
        case "ok":
          const successes = document.querySelector("#results .successes");
          let sc = parseInt(successes.innerText, 10);
          successes.innerText = (sc + 1).toString(10);
          const deets = el.querySelector(".details");
          if (!deets) {
            throw "invalid details for index [" + m.param.idx + "]";
          }
          const deetsDiv = document.createElement("div");
          deetsDiv.innerHTML = m.param.ctx.table;
          deets.replaceChildren(deetsDiv);

          const btn = el.querySelector(".modal-button");
          btn.classList.remove("hidden");

          const md = el.querySelector(".result-content");
          md.innerHTML = m.param.ctx.result;

          break;
        case "complete":
          document.querySelector("#results .elapsed").innerText = m.param.ctx.message;
          document.querySelector("#results .status").innerText = m.param.ctx.status;
          break;
        default:
          console.log("[Recv]", m.param.idx, m.cmd);
          break;
      }
    }
    function err(e) {
      console.log("[Err]", e);
    }
    document.addEventListener("DOMContentLoaded", function() {
      const up = new URLSearchParams(window.location.search);
      up.set("channel", "`)
//line views/vworkflow/Script.html:68
	qw422016.E().S(ch)
//line views/vworkflow/Script.html:68
	qw422016.N().S(`");
      sock = new loadtoad.Socket(false, open, recv, err, "`)
//line views/vworkflow/Script.html:69
	qw422016.E().S(pth)
//line views/vworkflow/Script.html:69
	qw422016.N().S(`?" + up.toString());
      console.log("[Load]");
    });
  </script>
`)
//line views/vworkflow/Script.html:73
}

//line views/vworkflow/Script.html:73
func writestartScript(qq422016 qtio422016.Writer, ch string, pth string) {
//line views/vworkflow/Script.html:73
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkflow/Script.html:73
	streamstartScript(qw422016, ch, pth)
//line views/vworkflow/Script.html:73
	qt422016.ReleaseWriter(qw422016)
//line views/vworkflow/Script.html:73
}

//line views/vworkflow/Script.html:73
func startScript(ch string, pth string) string {
//line views/vworkflow/Script.html:73
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkflow/Script.html:73
	writestartScript(qb422016, ch, pth)
//line views/vworkflow/Script.html:73
	qs422016 := string(qb422016.B)
//line views/vworkflow/Script.html:73
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkflow/Script.html:73
	return qs422016
//line views/vworkflow/Script.html:73
}
