// Code generated by qtc from "Start.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vworkflow/Start.html:1
package vworkflow

//line views/vworkflow/Start.html:1
import (
	"fmt"

	"github.com/kyleu/loadtoad/app"
	"github.com/kyleu/loadtoad/app/controller/cutil"
	"github.com/kyleu/loadtoad/app/lib/har"
	"github.com/kyleu/loadtoad/app/loadtoad"
	"github.com/kyleu/loadtoad/views/components"
	"github.com/kyleu/loadtoad/views/layout"
	"github.com/kyleu/loadtoad/views/vhar"
)

//line views/vworkflow/Start.html:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vworkflow/Start.html:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vworkflow/Start.html:13
type Start struct {
	layout.Basic
	Workflow *loadtoad.Workflow
	Entries  har.Entries
	Channel  string
	Path     string
}

//line views/vworkflow/Start.html:21
func (p *Start) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkflow/Start.html:21
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="#modal-workflow"><button type="button">JSON</button></a></div>
    `)
//line views/vworkflow/Start.html:24
	components.StreamJSONModal(qw422016, "workflow", "Workflow", p.Workflow, 3)
//line views/vworkflow/Start.html:24
	qw422016.N().S(`
    <h3>`)
//line views/vworkflow/Start.html:25
	components.StreamSVGRefIcon(qw422016, `sitemap`, ps)
//line views/vworkflow/Start.html:25
	qw422016.N().S(` `)
//line views/vworkflow/Start.html:25
	qw422016.E().S(p.Workflow.Title())
//line views/vworkflow/Start.html:25
	qw422016.N().S(` Results</h3>
    <div class="mt">
`)
//line views/vworkflow/Start.html:27
	if len(p.Entries) == 0 {
//line views/vworkflow/Start.html:27
		qw422016.N().S(`      <div><em>no entries</em></div>
`)
//line views/vworkflow/Start.html:29
	}
//line views/vworkflow/Start.html:29
	qw422016.N().S(`    </div>
    <div id="results" class="mt">
      <div>
        <strong>`)
//line views/vworkflow/Start.html:33
	qw422016.N().D(len(p.Entries))
//line views/vworkflow/Start.html:33
	qw422016.N().S(`</strong> total requests.
        <strong class="successes">0</strong> succeeded and <strong class="failures">0</strong> failed in <strong class="elapsed">0ms</strong>.
      </div>
      <div class="mt"><em class="status">Running...</em></div>
      <div class="logs"></div>
    </div>
  </div>
`)
//line views/vworkflow/Start.html:40
	for idx, e := range p.Entries {
//line views/vworkflow/Start.html:40
		qw422016.N().S(`  `)
//line views/vworkflow/Start.html:41
		streamentryPlaceholder(qw422016, idx, e, ps)
//line views/vworkflow/Start.html:41
		qw422016.N().S(`
`)
//line views/vworkflow/Start.html:42
	}
//line views/vworkflow/Start.html:42
	qw422016.N().S(`  `)
//line views/vworkflow/Start.html:43
	streamstartScript(qw422016, p.Channel, p.Path)
//line views/vworkflow/Start.html:43
	qw422016.N().S(`
`)
//line views/vworkflow/Start.html:44
}

//line views/vworkflow/Start.html:44
func (p *Start) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkflow/Start.html:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkflow/Start.html:44
	p.StreamBody(qw422016, as, ps)
//line views/vworkflow/Start.html:44
	qt422016.ReleaseWriter(qw422016)
//line views/vworkflow/Start.html:44
}

//line views/vworkflow/Start.html:44
func (p *Start) Body(as *app.State, ps *cutil.PageState) string {
//line views/vworkflow/Start.html:44
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkflow/Start.html:44
	p.WriteBody(qb422016, as, ps)
//line views/vworkflow/Start.html:44
	qs422016 := string(qb422016.B)
//line views/vworkflow/Start.html:44
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkflow/Start.html:44
	return qs422016
//line views/vworkflow/Start.html:44
}

//line views/vworkflow/Start.html:46
func streamentryPlaceholder(qw422016 *qt422016.Writer, idx int, ent *har.Entry, ps *cutil.PageState) {
//line views/vworkflow/Start.html:46
	qw422016.N().S(`
  <div id="entry-placeholder-`)
//line views/vworkflow/Start.html:47
	qw422016.N().D(idx)
//line views/vworkflow/Start.html:47
	qw422016.N().S(`" class="card">
    <div class="right">
      <a class="modal-button hidden" href="#modal-result-`)
//line views/vworkflow/Start.html:49
	qw422016.N().D(idx)
//line views/vworkflow/Start.html:49
	qw422016.N().S(`"><button type="button">Result</button></a>
      <a href="#modal-entry-`)
//line views/vworkflow/Start.html:50
	qw422016.N().D(idx)
//line views/vworkflow/Start.html:50
	qw422016.N().S(`"><button type="button">Details</button></a>
    </div>
    <div id="modal-result-`)
//line views/vworkflow/Start.html:52
	qw422016.N().D(idx)
//line views/vworkflow/Start.html:52
	qw422016.N().S(`" class="modal" style="display: none;">
      <a class="backdrop" href="#"></a>
      <div class="modal-content">
        <div class="modal-header">
          <a href="#" class="modal-close">×</a>
          <h2>Result [`)
//line views/vworkflow/Start.html:57
	qw422016.N().D(idx)
//line views/vworkflow/Start.html:57
	qw422016.N().S(`]: `)
//line views/vworkflow/Start.html:57
	qw422016.E().S(ent.String())
//line views/vworkflow/Start.html:57
	qw422016.N().S(`</h2>
        </div>
        <div class="modal-body">
          <div class="mt result-content">
            In progress...
          </div>
        </div>
      </div>
    </div>
    <h3>`)
//line views/vworkflow/Start.html:66
	components.StreamSVGRefIcon(qw422016, `file`, ps)
//line views/vworkflow/Start.html:66
	qw422016.E().S(ent.String())
//line views/vworkflow/Start.html:66
	qw422016.N().S(`</h3>
    <div class="clear"></div>
    <div class="mts details">
      <em>pending...</em>
    </div>
    <div class="logs">
    </div>
  </div>
  <div id="modal-entry-`)
//line views/vworkflow/Start.html:74
	qw422016.N().D(idx)
//line views/vworkflow/Start.html:74
	qw422016.N().S(`" class="modal" style="display: none;">
    <a class="backdrop" href="#"></a>
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="modal-close">×</a>
        <h2>`)
//line views/vworkflow/Start.html:79
	qw422016.E().S(ent.String())
//line views/vworkflow/Start.html:79
	qw422016.N().S(`</h2>
      </div>
      <div class="modal-body">
        `)
//line views/vworkflow/Start.html:82
	vhar.StreamRenderEntry(qw422016, fmt.Sprintf("%d", idx), ent, ps)
//line views/vworkflow/Start.html:82
	qw422016.N().S(`
      </div>
    </div>
  </div>
`)
//line views/vworkflow/Start.html:86
}

//line views/vworkflow/Start.html:86
func writeentryPlaceholder(qq422016 qtio422016.Writer, idx int, ent *har.Entry, ps *cutil.PageState) {
//line views/vworkflow/Start.html:86
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkflow/Start.html:86
	streamentryPlaceholder(qw422016, idx, ent, ps)
//line views/vworkflow/Start.html:86
	qt422016.ReleaseWriter(qw422016)
//line views/vworkflow/Start.html:86
}

//line views/vworkflow/Start.html:86
func entryPlaceholder(idx int, ent *har.Entry, ps *cutil.PageState) string {
//line views/vworkflow/Start.html:86
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkflow/Start.html:86
	writeentryPlaceholder(qb422016, idx, ent, ps)
//line views/vworkflow/Start.html:86
	qs422016 := string(qb422016.B)
//line views/vworkflow/Start.html:86
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkflow/Start.html:86
	return qs422016
//line views/vworkflow/Start.html:86
}
