// Code generated by qtc from "Start.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vworkflow/Start.html:1
package vworkflow

//line views/vworkflow/Start.html:1
import (
	"github.com/kyleu/loadtoad/app"
	"github.com/kyleu/loadtoad/app/controller/cutil"
	"github.com/kyleu/loadtoad/app/loadtoad"
	"github.com/kyleu/loadtoad/app/loadtoad/har"
	"github.com/kyleu/loadtoad/views/components"
	"github.com/kyleu/loadtoad/views/layout"
)

//line views/vworkflow/Start.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vworkflow/Start.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vworkflow/Start.html:10
type Start struct {
	layout.Basic
	Workflow *loadtoad.Workflow
	Entries  har.Entries
	Channel  string
	Path     string
}

//line views/vworkflow/Start.html:18
func (p *Start) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkflow/Start.html:18
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="#modal-workflow"><button type="button">JSON</button></a></div>
    `)
//line views/vworkflow/Start.html:21
	components.StreamJSONModal(qw422016, "workflow", "Workflow", p.Workflow, 3)
//line views/vworkflow/Start.html:21
	qw422016.N().S(`
    <h3>`)
//line views/vworkflow/Start.html:22
	components.StreamSVGRefIcon(qw422016, `sitemap`, ps)
//line views/vworkflow/Start.html:22
	qw422016.N().S(` `)
//line views/vworkflow/Start.html:22
	qw422016.E().S(p.Workflow.Title())
//line views/vworkflow/Start.html:22
	qw422016.N().S(` Results</h3>
    <div class="mt">
`)
//line views/vworkflow/Start.html:24
	if len(p.Entries) == 0 {
//line views/vworkflow/Start.html:24
		qw422016.N().S(`      <div><em>no entries</em></div>
`)
//line views/vworkflow/Start.html:26
	}
//line views/vworkflow/Start.html:26
	qw422016.N().S(`    </div>
    <div id="results" class="mt">
      <div>
        <strong>`)
//line views/vworkflow/Start.html:30
	qw422016.N().D(len(p.Entries))
//line views/vworkflow/Start.html:30
	qw422016.N().S(`</strong> total requests.
        <strong class="successes">0</strong> succeeded and <strong class="failures">0</strong> failed in <strong class="elapsed">0ms</strong>.
      </div>
      <div class="mt"><em class="status">Running...</em></div>
      <div class="logs"></div>
    </div>
  </div>
`)
//line views/vworkflow/Start.html:37
	for idx, e := range p.Entries {
//line views/vworkflow/Start.html:37
		qw422016.N().S(`  `)
//line views/vworkflow/Start.html:38
		streamentryPlaceholder(qw422016, idx, e, ps)
//line views/vworkflow/Start.html:38
		qw422016.N().S(`
`)
//line views/vworkflow/Start.html:39
	}
//line views/vworkflow/Start.html:39
	qw422016.N().S(`  `)
//line views/vworkflow/Start.html:40
	streamstartScript(qw422016, p.Channel, p.Path)
//line views/vworkflow/Start.html:40
	qw422016.N().S(`
`)
//line views/vworkflow/Start.html:41
}

//line views/vworkflow/Start.html:41
func (p *Start) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vworkflow/Start.html:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkflow/Start.html:41
	p.StreamBody(qw422016, as, ps)
//line views/vworkflow/Start.html:41
	qt422016.ReleaseWriter(qw422016)
//line views/vworkflow/Start.html:41
}

//line views/vworkflow/Start.html:41
func (p *Start) Body(as *app.State, ps *cutil.PageState) string {
//line views/vworkflow/Start.html:41
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkflow/Start.html:41
	p.WriteBody(qb422016, as, ps)
//line views/vworkflow/Start.html:41
	qs422016 := string(qb422016.B)
//line views/vworkflow/Start.html:41
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkflow/Start.html:41
	return qs422016
//line views/vworkflow/Start.html:41
}

//line views/vworkflow/Start.html:43
func streamentryPlaceholder(qw422016 *qt422016.Writer, idx int, ent *har.Entry, ps *cutil.PageState) {
//line views/vworkflow/Start.html:43
	qw422016.N().S(`
  <div id="entry-placeholder-`)
//line views/vworkflow/Start.html:44
	qw422016.N().D(idx)
//line views/vworkflow/Start.html:44
	qw422016.N().S(`" class="card">
    <h3>`)
//line views/vworkflow/Start.html:45
	components.StreamSVGRefIcon(qw422016, `file`, ps)
//line views/vworkflow/Start.html:45
	qw422016.E().S(ent.String())
//line views/vworkflow/Start.html:45
	qw422016.N().S(`</h3>
    <div class="clear"></div>
    <div class="mts details">
      <em>pending...</em>
    </div>
    <div class="logs">
    </div>
  </div>
`)
//line views/vworkflow/Start.html:53
}

//line views/vworkflow/Start.html:53
func writeentryPlaceholder(qq422016 qtio422016.Writer, idx int, ent *har.Entry, ps *cutil.PageState) {
//line views/vworkflow/Start.html:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vworkflow/Start.html:53
	streamentryPlaceholder(qw422016, idx, ent, ps)
//line views/vworkflow/Start.html:53
	qt422016.ReleaseWriter(qw422016)
//line views/vworkflow/Start.html:53
}

//line views/vworkflow/Start.html:53
func entryPlaceholder(idx int, ent *har.Entry, ps *cutil.PageState) string {
//line views/vworkflow/Start.html:53
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vworkflow/Start.html:53
	writeentryPlaceholder(qb422016, idx, ent, ps)
//line views/vworkflow/Start.html:53
	qs422016 := string(qb422016.B)
//line views/vworkflow/Start.html:53
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vworkflow/Start.html:53
	return qs422016
//line views/vworkflow/Start.html:53
}
