// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vhar/Detail.html:1
package vhar

//line views/vhar/Detail.html:1
import (
	"github.com/kyleu/loadtoad/app"
	"github.com/kyleu/loadtoad/app/controller/cutil"
	"github.com/kyleu/loadtoad/app/loadtoad/har"
	"github.com/kyleu/loadtoad/app/util"
	"github.com/kyleu/loadtoad/views/components"
	"github.com/kyleu/loadtoad/views/layout"
)

//line views/vhar/Detail.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vhar/Detail.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vhar/Detail.html:10
type Detail struct {
	layout.Basic
	Har *har.Log
}

//line views/vhar/Detail.html:15
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vhar/Detail.html:15
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/vhar/Detail.html:17
	components.StreamSVGRefIcon(qw422016, `book`, ps)
//line views/vhar/Detail.html:17
	qw422016.N().S(` `)
//line views/vhar/Detail.html:17
	qw422016.E().S(p.Har.Key)
//line views/vhar/Detail.html:17
	qw422016.N().S(`</h3>
    <div class="mt">
      `)
//line views/vhar/Detail.html:19
	qw422016.E().S(util.MicrosToMillis(p.Har.Entries.TotalDuration()))
//line views/vhar/Detail.html:19
	qw422016.N().S(` elapsed, downloaded `)
//line views/vhar/Detail.html:19
	qw422016.E().S(util.ByteSizeSI(int64(p.Har.Entries.TotalResponseBodySize())))
//line views/vhar/Detail.html:19
	qw422016.N().S(`
    </div>
  </div>

  <div class="card">
    <h3>`)
//line views/vhar/Detail.html:24
	qw422016.N().D(len(p.Har.Entries))
//line views/vhar/Detail.html:24
	qw422016.N().S(` `)
//line views/vhar/Detail.html:24
	qw422016.E().S(util.StringPluralMaybe("Entry", len(p.Har.Entries)))
//line views/vhar/Detail.html:24
	qw422016.N().S(`</h3>
    <div class="mts">
      <ul class="accordion">
`)
//line views/vhar/Detail.html:27
	for i, e := range p.Har.Entries {
//line views/vhar/Detail.html:28
		e = e.Cleaned()

//line views/vhar/Detail.html:28
		qw422016.N().S(`        <li>
          <input id="accordion-entry-`)
//line views/vhar/Detail.html:30
		qw422016.N().D(i)
//line views/vhar/Detail.html:30
		qw422016.N().S(`" type="checkbox" hidden />
          <label for="accordion-entry-`)
//line views/vhar/Detail.html:31
		qw422016.N().D(i)
//line views/vhar/Detail.html:31
		qw422016.N().S(`">
            `)
//line views/vhar/Detail.html:32
		StreamRenderEntryOptions(qw422016, i, e, false)
//line views/vhar/Detail.html:32
		qw422016.N().S(`
            `)
//line views/vhar/Detail.html:33
		components.StreamExpandCollapse(qw422016, 3, ps)
//line views/vhar/Detail.html:33
		qw422016.N().S(` `)
//line views/vhar/Detail.html:33
		qw422016.E().S(e.String())
//line views/vhar/Detail.html:33
		qw422016.N().S(`
            <div class="clear"></div>
          </label>
          <div class="bd">
            `)
//line views/vhar/Detail.html:37
		StreamRenderEntry(qw422016, i, e, ps)
//line views/vhar/Detail.html:37
		qw422016.N().S(`
          </div>
        </li>
`)
//line views/vhar/Detail.html:40
	}
//line views/vhar/Detail.html:40
	qw422016.N().S(`      </ul>
    </div>
  </div>
  <script>
    function clip(k) {
      if (!navigator.clipboard) {
        return;
      }
      const el = document.getElementById("modal-entry-" + k + "-curl-data");
      navigator.clipboard.writeText(el.innerText);
    }
  </script>
`)
//line views/vhar/Detail.html:53
}

//line views/vhar/Detail.html:53
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vhar/Detail.html:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhar/Detail.html:53
	p.StreamBody(qw422016, as, ps)
//line views/vhar/Detail.html:53
	qt422016.ReleaseWriter(qw422016)
//line views/vhar/Detail.html:53
}

//line views/vhar/Detail.html:53
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vhar/Detail.html:53
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhar/Detail.html:53
	p.WriteBody(qb422016, as, ps)
//line views/vhar/Detail.html:53
	qs422016 := string(qb422016.B)
//line views/vhar/Detail.html:53
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhar/Detail.html:53
	return qs422016
//line views/vhar/Detail.html:53
}
