// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vhar/Detail.html:1
package vhar

//line views/vhar/Detail.html:1
import (
	"fmt"

	"github.com/kyleu/loadtoad/app"
	"github.com/kyleu/loadtoad/app/controller/cutil"
	"github.com/kyleu/loadtoad/app/loadtoad/har"
	"github.com/kyleu/loadtoad/app/util"
	"github.com/kyleu/loadtoad/views/components"
	"github.com/kyleu/loadtoad/views/layout"
)

//line views/vhar/Detail.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vhar/Detail.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vhar/Detail.html:12
type Detail struct {
	layout.Basic
	Har *har.Log
}

//line views/vhar/Detail.html:17
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vhar/Detail.html:17
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/vhar/Detail.html:19
	components.StreamSVGRefIcon(qw422016, `book`, ps)
//line views/vhar/Detail.html:19
	qw422016.N().S(` `)
//line views/vhar/Detail.html:19
	qw422016.E().S(p.Har.Key)
//line views/vhar/Detail.html:19
	qw422016.N().S(`</h3>
  </div>

  <div class="card">
    <h3>`)
//line views/vhar/Detail.html:23
	qw422016.N().D(len(p.Har.Entries))
//line views/vhar/Detail.html:23
	qw422016.N().S(` `)
//line views/vhar/Detail.html:23
	qw422016.E().S(util.StringPluralMaybe("entry", len(p.Har.Entries)))
//line views/vhar/Detail.html:23
	qw422016.N().S(`</h3>
    <div class="mts">
      <ul class="accordion">
`)
//line views/vhar/Detail.html:26
	for i, e := range p.Har.Entries {
//line views/vhar/Detail.html:26
		qw422016.N().S(`        <li>
          <input id="accordion-entry-`)
//line views/vhar/Detail.html:28
		qw422016.N().D(i)
//line views/vhar/Detail.html:28
		qw422016.N().S(`" type="checkbox" hidden />
          <label for="accordion-entry-`)
//line views/vhar/Detail.html:29
		qw422016.N().D(i)
//line views/vhar/Detail.html:29
		qw422016.N().S(`">
            <div class="right"><a href="#modal-entry-`)
//line views/vhar/Detail.html:30
		qw422016.N().D(i)
//line views/vhar/Detail.html:30
		qw422016.N().S(`"><button type="button">JSON</button></a></div>
            `)
//line views/vhar/Detail.html:31
		components.StreamJSONModal(qw422016, fmt.Sprintf("entry-%d", i), e.String(), e, 3)
//line views/vhar/Detail.html:31
		qw422016.N().S(`
            `)
//line views/vhar/Detail.html:32
		components.StreamExpandCollapse(qw422016, 3, ps)
//line views/vhar/Detail.html:32
		qw422016.N().S(` `)
//line views/vhar/Detail.html:32
		qw422016.E().S(e.String())
//line views/vhar/Detail.html:32
		qw422016.N().S(`
            <div class="clear"></div>
          </label>
          <div class="bd">
            `)
//line views/vhar/Detail.html:36
		streamrenderEntry(qw422016, i, e, ps)
//line views/vhar/Detail.html:36
		qw422016.N().S(`
          </div>
        </li>
`)
//line views/vhar/Detail.html:39
	}
//line views/vhar/Detail.html:39
	qw422016.N().S(`      </ul>
    </div>
  </div>
`)
//line views/vhar/Detail.html:43
}

//line views/vhar/Detail.html:43
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vhar/Detail.html:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhar/Detail.html:43
	p.StreamBody(qw422016, as, ps)
//line views/vhar/Detail.html:43
	qt422016.ReleaseWriter(qw422016)
//line views/vhar/Detail.html:43
}

//line views/vhar/Detail.html:43
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vhar/Detail.html:43
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhar/Detail.html:43
	p.WriteBody(qb422016, as, ps)
//line views/vhar/Detail.html:43
	qs422016 := string(qb422016.B)
//line views/vhar/Detail.html:43
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhar/Detail.html:43
	return qs422016
//line views/vhar/Detail.html:43
}

//line views/vhar/Detail.html:45
func streamrenderEntry(qw422016 *qt422016.Writer, i int, e *har.Entry, ps *cutil.PageState) {
//line views/vhar/Detail.html:45
	qw422016.N().S(`
  <table>
    <tbody>
      <tr>
        <th class="shrink">Duration</th>
        <td>`)
//line views/vhar/Detail.html:50
	qw422016.E().S(e.Duration())
//line views/vhar/Detail.html:50
	qw422016.N().S(`</td>
      </tr>
      <tr>
        <th class="shrink">Request</th>
        <td>`)
//line views/vhar/Detail.html:54
	streamrenderRequest(qw422016, i, e.Request, ps)
//line views/vhar/Detail.html:54
	qw422016.N().S(`</td>
      </tr>
      <tr>
        <th class="shrink">Response</th>
        <td>`)
//line views/vhar/Detail.html:58
	streamrenderResponse(qw422016, i, e.Response, ps)
//line views/vhar/Detail.html:58
	qw422016.N().S(`</td>
      </tr>
    </tbody>
  </table>
`)
//line views/vhar/Detail.html:62
}

//line views/vhar/Detail.html:62
func writerenderEntry(qq422016 qtio422016.Writer, i int, e *har.Entry, ps *cutil.PageState) {
//line views/vhar/Detail.html:62
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhar/Detail.html:62
	streamrenderEntry(qw422016, i, e, ps)
//line views/vhar/Detail.html:62
	qt422016.ReleaseWriter(qw422016)
//line views/vhar/Detail.html:62
}

//line views/vhar/Detail.html:62
func renderEntry(i int, e *har.Entry, ps *cutil.PageState) string {
//line views/vhar/Detail.html:62
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhar/Detail.html:62
	writerenderEntry(qb422016, i, e, ps)
//line views/vhar/Detail.html:62
	qs422016 := string(qb422016.B)
//line views/vhar/Detail.html:62
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhar/Detail.html:62
	return qs422016
//line views/vhar/Detail.html:62
}

//line views/vhar/Detail.html:64
func streamrenderRequest(qw422016 *qt422016.Writer, i int, r *har.Request, ps *cutil.PageState) {
//line views/vhar/Detail.html:64
	qw422016.N().S(`
  <ul class="accordion">
    <li>
      <input id="accordion-request-`)
//line views/vhar/Detail.html:67
	qw422016.N().D(i)
//line views/vhar/Detail.html:67
	qw422016.N().S(`" type="checkbox" hidden />
      <label class="no-padding" for="accordion-request-`)
//line views/vhar/Detail.html:68
	qw422016.N().D(i)
//line views/vhar/Detail.html:68
	qw422016.N().S(`"><em>(click to show)</em></label>
      <div class="bd">`)
//line views/vhar/Detail.html:69
	components.StreamJSON(qw422016, r)
//line views/vhar/Detail.html:69
	qw422016.N().S(`</div>
    </li>
  </ul>
`)
//line views/vhar/Detail.html:72
}

//line views/vhar/Detail.html:72
func writerenderRequest(qq422016 qtio422016.Writer, i int, r *har.Request, ps *cutil.PageState) {
//line views/vhar/Detail.html:72
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhar/Detail.html:72
	streamrenderRequest(qw422016, i, r, ps)
//line views/vhar/Detail.html:72
	qt422016.ReleaseWriter(qw422016)
//line views/vhar/Detail.html:72
}

//line views/vhar/Detail.html:72
func renderRequest(i int, r *har.Request, ps *cutil.PageState) string {
//line views/vhar/Detail.html:72
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhar/Detail.html:72
	writerenderRequest(qb422016, i, r, ps)
//line views/vhar/Detail.html:72
	qs422016 := string(qb422016.B)
//line views/vhar/Detail.html:72
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhar/Detail.html:72
	return qs422016
//line views/vhar/Detail.html:72
}

//line views/vhar/Detail.html:74
func streamrenderResponse(qw422016 *qt422016.Writer, i int, r *har.Response, ps *cutil.PageState) {
//line views/vhar/Detail.html:74
	qw422016.N().S(`
  <ul class="accordion">
    <li>
      <input id="accordion-response-`)
//line views/vhar/Detail.html:77
	qw422016.N().D(i)
//line views/vhar/Detail.html:77
	qw422016.N().S(`" type="checkbox" hidden />
      <label class="no-padding" for="accordion-response-`)
//line views/vhar/Detail.html:78
	qw422016.N().D(i)
//line views/vhar/Detail.html:78
	qw422016.N().S(`"><em>(click to show)</em></label>
      <div class="bd">`)
//line views/vhar/Detail.html:79
	components.StreamJSON(qw422016, r)
//line views/vhar/Detail.html:79
	qw422016.N().S(`</div>
    </li>
  </ul>
`)
//line views/vhar/Detail.html:82
}

//line views/vhar/Detail.html:82
func writerenderResponse(qq422016 qtio422016.Writer, i int, r *har.Response, ps *cutil.PageState) {
//line views/vhar/Detail.html:82
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhar/Detail.html:82
	streamrenderResponse(qw422016, i, r, ps)
//line views/vhar/Detail.html:82
	qt422016.ReleaseWriter(qw422016)
//line views/vhar/Detail.html:82
}

//line views/vhar/Detail.html:82
func renderResponse(i int, r *har.Response, ps *cutil.PageState) string {
//line views/vhar/Detail.html:82
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhar/Detail.html:82
	writerenderResponse(qb422016, i, r, ps)
//line views/vhar/Detail.html:82
	qs422016 := string(qb422016.B)
//line views/vhar/Detail.html:82
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhar/Detail.html:82
	return qs422016
//line views/vhar/Detail.html:82
}
