// Code generated by qtc from "Response.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vhar/Response.html:1
package vhar

//line views/vhar/Response.html:1
import (
	"github.com/kyleu/loadtoad/app/controller/cutil"
	"github.com/kyleu/loadtoad/app/loadtoad/har"
	"github.com/kyleu/loadtoad/views/components"
)

//line views/vhar/Response.html:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vhar/Response.html:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vhar/Response.html:7
func streamrenderResponse(qw422016 *qt422016.Writer, i int, r *har.Response, ps *cutil.PageState) {
//line views/vhar/Response.html:7
	qw422016.N().S(`
  <ul class="accordion">
    <li>
      <input id="accordion-response-`)
//line views/vhar/Response.html:10
	qw422016.N().D(i)
//line views/vhar/Response.html:10
	qw422016.N().S(`" type="checkbox" hidden />
      <label class="no-padding" for="accordion-response-`)
//line views/vhar/Response.html:11
	qw422016.N().D(i)
//line views/vhar/Response.html:11
	qw422016.N().S(`"><em>(click to show)</em></label>
      <div class="bd">`)
//line views/vhar/Response.html:12
	components.StreamJSON(qw422016, r)
//line views/vhar/Response.html:12
	qw422016.N().S(`</div>
    </li>
  </ul>
`)
//line views/vhar/Response.html:15
}

//line views/vhar/Response.html:15
func writerenderResponse(qq422016 qtio422016.Writer, i int, r *har.Response, ps *cutil.PageState) {
//line views/vhar/Response.html:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhar/Response.html:15
	streamrenderResponse(qw422016, i, r, ps)
//line views/vhar/Response.html:15
	qt422016.ReleaseWriter(qw422016)
//line views/vhar/Response.html:15
}

//line views/vhar/Response.html:15
func renderResponse(i int, r *har.Response, ps *cutil.PageState) string {
//line views/vhar/Response.html:15
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhar/Response.html:15
	writerenderResponse(qb422016, i, r, ps)
//line views/vhar/Response.html:15
	qs422016 := string(qb422016.B)
//line views/vhar/Response.html:15
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhar/Response.html:15
	return qs422016
//line views/vhar/Response.html:15
}
