# Content managed by Project Forge, see [projectforge.md] for details.
name: playwright
on:
  push:
    tags:
      - "*"
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  playwright:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - name: "Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: 18

      - name: "Install dependencies"
        working-directory: "./test/playwright"
        run: "npm ci"

      - name: "Install Playwright Browsers"
        working-directory: "./test/playwright"
        run: "npx playwright install --with-deps"

      - name: "Golang"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.21"

      - name: "Cache"
        uses: "actions/cache@v2"
        with:
          path: "~/go/pkg/mod"
          key: "${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Bootstrap"
        run: "bin/bootstrap.sh"

      - name: "Build App"
        run: "bin/build/playwright.sh"

      - name: "Run Playwright tests"
        working-directory: "./test/playwright"
        run: "npx playwright test"

      - name: "Upload report"
        uses: "actions/upload-artifact@v2"
        with:
          name: "github-pages"
          path: "./test/playwright/playwright-report/"
          retention-days: 30

  deploy:
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    permissions:
      pages: write
      id-token: write
    runs-on: "ubuntu-latest"
    needs: "playwright"
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v2"
        with:
          artifact_name: "github-pages"
